import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Preloader from "./components/Preloader";
import { Play } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"

// In your layout
<Toaster />
import { ClerkProvider } from '@clerk/nextjs'

const play = Play({
 
  weight: "400",
  variable: "--font-play",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${play.variable} antialiased`} 
      >
        <Preloader /> 
        <Navbar />
        {children}
        <Toaster/>
      </body>
    </html>
    </ClerkProvider>
  );
}