import type { Metadata } from "next";
import { Play } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";


const play = Play({
  subsets: ['latin'],
  weight: ['400', '700'], 
  display: 'swap',
  variable: '--play',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
      <body
        className={` ${play.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
